### ISSUE TITLE
Windows no longer compiles

### ISSUE THREAD

**Issue by FGasper** [FGasper/p5-Net-LibNFS#11]
libnfs appears, in https://github.com/sahlberg/libnfs/commit/028cff9ac03a8d767939cc630c515886192b43ae, to have broken this module on Windows.

I’m unsure of the fix presently. While libnfs itself _builds_ on Windows, its internal `writev` implementation doesn’t seem to work for this module.

**Comment by FGasper** [comment]
I’ve tried setting that implementation to be non-`inline`, but that didn’t fix the situation. I either see “missing symbol”, or multiple-definition errors, for `writev`.

**Comment by FGasper** [comment]
@rovo89, do you have any insight here?

**Comment by rovo89** [comment]
Unfortunately I don't have a test environment, so I can just check the actions... I assume the latest one is this:
https://github.com/FGasper/p5-Net-LibNFS/actions/runs/3593949367/jobs/6051579223

And there the error is:
```
libnfs.xs: In function '_set_unix_authn':
libnfs.xs:806:78: error: expected ')' before 'PRIu32'
  806 |     if (value > UINT32_MAX) croak("%s: value (%" UVuf ") exceeds maximum (%" PRIu32 ")", name, value, UINT32_MAX);
      |                                  ~                                           ^~~~~~
libnfs.xs:806:78: note: in definition of macro '_croak_if_uv_exceeds_u32'
  806 |     if (value > UINT32_MAX) croak("%s: value (%" UVuf ") exceeds maximum (%" PRIu32 ")", name, value, UINT32_MAX);
      |                                                                              ^~~~~~
libnfs.xs:31:1: note: 'PRIu32' is defined in header '<inttypes.h>'; did you forget to '#include <inttypes.h>'?
   30 | #include <fcntl.h>
  +++ |+#include <inttypes.h>
```

Maybe try the suggestion, or maybe use `UVuf` instead of `PRIu32`? I don't know the definition, but if it can represent `value`, then it should be able to represent the smaller `UINT32_MAX` as well.

**Comment by FGasper** [comment]
Oof, that’s _another_ issue, but at least probably an easy one to accommodate.

**Comment by FGasper** [comment]
The “real” problem is `writev` and `readv`, which don’t exist in Windows-land. libnfs _builds_ in Windows just fine, but when I try to link libnfs.a into Net::LibNFS I get the linker error that writev and readv don’t exist.

**Comment by rovo89** [comment]
Difficult... are we even sure that `win32_compat.h` is included? Maybe https://github.com/marketplace/actions/debugging-with-ssh helps to debug this on the runner itself?

**Comment by FGasper** [comment]
Notwithstanding the love that that action inspires in me (!!) …
![image](https://user-images.githubusercontent.com/844867/205143231-83101a20-9e83-444f-b07d-4f59431c207a.png)

**Comment by FGasper** [comment]
I think I can get access to a Windows VM; hopefully that’ll yield some answers.

**Comment by FGasper** [comment]
@rovo89 This seems to do it: https://github.com/sahlberg/libnfs/pull/411/files

**Comment by FGasper** [comment]
Fixed via update to libnfs.
